[package]
name = "mcp-relay"
version = "0.1.0"
edition = "2021"

[dependencies]
rmcp = { version = "0.1.2", features = ["client", "transport-sse", "transport-child-process"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rand = "0.8"
futures = "0.3"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
axum = { version = "0.8", features = ["macros"] }
tokio-stream = { version = "0.1" }
tokio-util = { version = "0.7", features = ["codec"] }
http = "1.3"
base64 = "0.22"

[[bin]]
name = "mcp-relay"
path = "main.rs"
