kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: mcp
spec:
  controllerName: kgateway.dev/kgateway
  parametersRef:
    group: gateway.kgateway.dev
    kind: GatewayParameters
    name: kgateway
    namespace: default
---
kind: GatewayParameters
apiVersion: gateway.kgateway.dev/v1alpha1
metadata:
  name: kgateway
spec:
  selfManaged: {}
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: mcp-gateway
spec:
  gatewayClassName: mcp
  listeners:
  - protocol: kgateway.dev/mcp
    port: 8080
    name: http
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-gateway
spec:
  selector:
    matchLabels:
      app: mcp-gateway
  template:
    metadata:
      labels:
        app: mcp-gateway
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: mcp-gateway
          image: ctlptl-registry:5000/mcp-gateway:latest
          args:
            - --file=/config/config.json
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: GW_NAME
              value:  mcp-gateway
            - name: RUST_BACKTRACE
              value: "1"
            - name: RUST_LOG
              value: debug
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: mcp-gateway-config

---
apiVersion: v1
kind: Service
metadata:
  name: mcp-gateway
spec:
  selector:
    app: mcp-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-gateway-config
data:
  config.json: |
    {
      "type": "xds",
      "xds_address": "http://kgateway.kgateway-system.svc.cluster.local:9977",
      "metadata": {},
      "alt_xds_hostname": "mcp-gateway.default.svc.cluster.local",
      "listener": {
        "type": "sse",
        "host": "0.0.0.0",
        "port": 8080,
        "authn": {
          "type":"jwt",
          "issuer": ["me"],
          "audience": ["me.com"],
            "jwks": {
              "type": "local",
                "source":
                  { "type": "file", "data": "/config/jwks.json" }
                }
        }
      }
    }
  jwks.json: |
    {
      "use": "sig",
      "kty": "EC",
      "kid": "XhO06x8JjWH1wwkWkyeEUxsooGEWoEdidEpwyd_hmuI",
      "crv": "P-256",
      "alg": "ES256",
      "x": "XZHF8Em5LbpqfgewAalpSEH4Ka2I2xjcxxUt2j6-lCo",
      "y": "g3DFz45A7EOUMgmsNXatrXw1t-PG5xsbkxUs851RxSE"
    }

---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: MCPAuthPolicy
metadata:
  name: mcp-gateway-auth
spec:
  targetRefs:
  - name: mcp-gateway
    group: gateway.networking.k8s.io
    kind: Gateway
  rules:
    - matches:
      - type: JWT
        jwt:
          claim: sub
          value: me
      resource:
        kind: tool
        name: default/mcp-everything:echo
