apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-proxy
spec:
  selector:
    matchLabels:
      app: mcp-proxy
  template:
    metadata:
      labels:
        app: mcp-proxy
    spec:
      containers:
        - name: mcp-proxy
          image: localhost:5000/mcp-proxy:latest
          command:
            - mcp-proxy
            - --config=/config/config.yaml
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: mcp-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-proxy
spec:
  selector:
    app: mcp-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-proxy-config
data:
  config.yaml: |
    listener:
      sse:
        host: 0.0.0.0
        port: 8001
    rules: []
    targets:
      local:
        stdio:
          args:
          - '@modelcontextprotocol/server-everything'
          cmd: npx

#      remote:
#        sse:
#          host: mcp-everything
#          port: 80
