name: Tag and Push 

on:
  push:
    tags:
    - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'

jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build
      run: |
        # if workflow_dispatch is used, use the version input
        if [ -n "${{ github.event.inputs.version }}" ]; then
          export VERSION=${{ github.event.inputs.version }}
        else
          export VERSION=$(echo "$GITHUB_REF" | cut -c12-)
        fi
        docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/mcpproxy-dev/mcp-relay:${VERSION} --push .
  release:
    needs:
    - push-image
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')